const test = require('ava')
const log = require('fliplog')
const DLL = require('../')

test.todo('stale')
test.todo('shouldBeBuilt')
test.todo('shouldBeUsed')
test.todo('output')
test.todo('debug does output')
test.todo('og returns original')
